#!/bin/bash
#
# This script is designed to be run inside the container
#

export USER={{ .openstack_database_adminUser }}
export PASS={{ .openstack_database_adminPass }}
export HOST={{ .openstack_database_host }}
export PORT={{ .openstack_database_port }}

mysql -u ${USER} -p${PASS} -h ${HOST} -P ${PORT} -e 'CREATE DATABASE glance;' || echo 'database exists'
mysql -u ${USER} -p${PASS} -h ${HOST} -P ${PORT} -e 'CREATE USER {{ .openstack_glance_databaseUser }};' || echo 'user exists'
mysql -u ${USER} -p${PASS} -h ${HOST} -P ${PORT} -e 'GRANT ALL PRIVILEGES ON glance.* TO "{{ .openstack_glance_databaseUser }}"@"%";'
mysql -u ${USER} -p${PASS} -h ${HOST} -P ${PORT} -e 'SET PASSWORD FOR {{ .openstack_glance_databaseUser }}@"%"=PASSWORD("{{ .openstack_glance_databasePass }}");'

exit 0