#!/bin/bash
#
# This script is designed to be run inside the container
#

until mysql -e 'select now();' > /dev/null; do
  echo "Wating for Database on $HOST to listen on $PORT"
  sleep 5
done

mysql -e 'CREATE DATABASE glance;' || true
mysql -e 'GRANT ALL PRIVILEGES ON glance.* TO "{{ getv "/openstack/glance/databaseUser" }}"@"%" IDENTIFIED BY "{{ getv "/openstack/glance/databasePass" }}";'

exit 0
