#!/bin/sh

export OS_USERNAME={{ getv "/openstack/keystone/adminUser" }}
export OS_PASSWORD={{ getv "/openstack/keystone/adminPass" }}
export OS_TENANT_NAME={{ getv "/openstack/keystone/adminTenant" }}
export OS_AUTH_URL=http://{{ getv "/openstack/keystone/host" }}:{{ getv "/openstack/keystone/port" }}/v2.0
