#!/bin/bash
#
# This script is designed to be run inside the container
#

until mysql -e 'SELECT NOW();'; do
  echo "Wating for Database on $HOST to listen on $PORT"
  sleep 5
done

mysql -e 'CREATE DATABASE keystone;' || true
mysql -e 'GRANT ALL PRIVILEGES ON keystone.* TO "{{ getv "/openstack/keystone/databaseUser" }}"@"%" IDENTIFIED BY "{{ getv "/openstack/keystone/databasePass" }}";'

exit 0
