#!/bin/bash
#
# This script is designed to be run inside the container
#

export USER={{ .openstack_database_adminUser }}
export PASS={{ .openstack_database_adminPass }}
export HOST={{ .openstack_database_host }}
export PORT={{ .openstack_database_port }}

mysql -u ${USER} -p${PASS} -h ${HOST} -P ${PORT} -e 'CREATE DATABASE keystone;' || echo 'database exists'
mysql -u ${USER} -p${PASS} -h ${HOST} -P ${PORT} -e 'CREATE USER {{ .openstack_keystone_databaseUser }};' || echo 'user exists'
mysql -u ${USER} -p${PASS} -h ${HOST} -P ${PORT} -e 'GRANT ALL PRIVILEGES ON keystone.* TO "{{ .openstack_keystone_databaseUser }}"@"%";'
mysql -u ${USER} -p${PASS} -h ${HOST} -P ${PORT} -e 'SET PASSWORD FOR {{ .openstack_keystone_databaseUser }}@"%"=PASSWORD("{{ .openstack_keystone_databasePass }}");'

exit 0