#!/bin/sh

export OS_USERNAME={{ getv "/openstack/keystone/adminUser" }}
export OS_PASSWORD={{ getv "/openstack/keystone/adminPass" }}
export OS_TENANT_NAME={{ getv "/openstack/keystone/adminTenant" }}
export OS_AUTH_URL=http://127.0.0.1:5000/v2.0
