#!/bin/sh

export OS_USERNAME={{ .openstack_keystone_adminUser }}
export OS_PASSWORD={{ .openstack_keystone_adminPass }}
export OS_TENANT_NAME={{ .openstack_keystone_adminTenant }}
export OS_AUTH_URL=http://{{ .openstack_keystone_host }}:{{ .openstack_keystone_port }}/v2.0
