#!/bin/bash
#
# Grant various credentials to mysql before joining cluster
#

rabbitmqctl add_user {{ .openstack_messaging_credentials_adminUser }} {{ .openstack_messaging_credentials_adminPass }}
rabbitmqctl add_user {{ .openstack_messaging_credentials_openstackUser }} {{ .openstack_messaging_credentials_openstackPass }}
rabbitmqctl set_user_tags {{ .openstack_messaging_credentials_adminUser }} administrator

{{range $vhost := .openstack_messaging_vhosts }}
    rabbitmqctl add_vhost {{$vhost.Value}}
    rabbitmqctl set_permissions -p {{$vhost.Value}} {{ .openstack_messaging_credentials_openstackUser }} "*" ".*" ".*"
{{end}}

exit 0